//
//  ViewRegistro.swift
//  BookieApp
//
//  Created by dam2 on 15/3/24.
//

import SwiftUI

struct ViewRegistro: View {
  var body: some View {
    ZStack() {
      ZStack() {
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 353, height: 51)
          .background(Color(red: 0.98, green: 0.86, blue: 0.74))
          .cornerRadius(24)
          .offset(x: 0, y: 15.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 19.04, height: 21.19)
          .background(
            AsyncImage(url: URL(string: "https://via.placeholder.com/19x21"))
          )
          .cornerRadius(24)
          .offset(x: 146.02, y: 15.59)
        Text("Repetir contraseña")
          .font(Font.custom("Capriola", size: 16))
          .foregroundColor(.black)
          .offset(x: -70.07, y: -30.50)
      }
      .frame(width: 353, height: 82)
      .offset(x: 0, y: 119)
      ZStack() {
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 353, height: 51)
          .background(Color(red: 0.98, green: 0.86, blue: 0.74))
          .cornerRadius(24)
          .offset(x: 0, y: 15.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 19.04, height: 21.19)
          .background(
            AsyncImage(url: URL(string: "https://via.placeholder.com/19x21"))
          )
          .cornerRadius(24)
          .offset(x: 146.02, y: 15.59)
        Text("Contraseña")
          .font(Font.custom("Capriola", size: 16))
          .foregroundColor(.black)
          .offset(x: -70.07, y: -30.50)
      }
      .frame(width: 353, height: 82)
      .offset(x: 0, y: -13)
      ZStack() {
        Text("Email")
          .font(Font.custom("Capriola", size: 16))
          .foregroundColor(.black)
          .offset(x: -70.07, y: -30.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 353, height: 51)
          .background(Color(red: 0.98, green: 0.86, blue: 0.74))
          .cornerRadius(24)
          .offset(x: 0, y: 15.50)
      }
      .frame(height: 82)
      .offset(x: -1, y: -145)
      Text("Recuperación de contraseña")
        .font(Font.custom("Capriola", size: 30))
        .foregroundColor(.black)
        .offset(x: -0.50, y: -288)
      Text("<")
        .font(Font.custom("Balsamiq Sans", size: 35))
        .foregroundColor(.black)
        .offset(x: -149, y: -375)
      ZStack() {
        Group {
          ZStack() {
            Rectangle()
              .foregroundColor(.clear)
              .frame(width: 203, height: 56.68)
              .background(Color(red: 0.99, green: 0.63, blue: 0.49))
              .cornerRadius(20)
              .offset(x: 0, y: 0)
              
            Text("Continuar")
              .font(Font.custom("Capriola", size: 16))
              .foregroundColor(.white)
              .offset(x: 0.55, y: -0.84)
          }
          .frame(width: 203, height: 56.68)
          .offset(x: 0.50, y: 6.50)

            .offset(x: 0, y: -14.84)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 15, height: 8)
            .background(.white)
            .offset(x: -88.50, y: -13.84)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 15, height: 8)
            .background(.white)
            .offset(x: -88.50, y: -13.84)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: -52.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: -63.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: -75.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 46.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 81.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 8)
            .background(.white)
            .offset(x: 90.50, y: -13.84)
        };Group {
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 70.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 58.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 3.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 38.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 27.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: 15.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: -41.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: -6.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: -17.50, y: -14.34)
          Ellipse()
            .foregroundColor(.clear)
            .frame(width: 13, height: 9)
            .background(.white)
            .offset(x: -29.50, y: -14.34)
        };Group {
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.95, green: 0.23, blue: 0.23), lineWidth: 1)
            )
            .offset(x: -76.39, y: -18.84)
            .rotationEffect(.degrees(-33.69))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.95, green: 0.23, blue: 0.23), lineWidth: 1)
            )
            .offset(x: -43.33, y: -13.75)
            .rotationEffect(.degrees(35.44))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.35, green: 0.86, blue: 0.68), lineWidth: 1)
            )
            .offset(x: -59.39, y: -13.66)
            .rotationEffect(.degrees(35.44))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.35, green: 0.86, blue: 0.68), lineWidth: 1)
            )
            .offset(x: 84.61, y: -11.66)
            .rotationEffect(.degrees(35.44))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.35, green: 0.86, blue: 0.68), lineWidth: 1)
            )
            .offset(x: 29.61, y: -14.66)
            .rotationEffect(.degrees(35.44))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.35, green: 0.86, blue: 0.68), lineWidth: 1)
            )
            .offset(x: 59.61, y: -13.66)
            .rotationEffect(.degrees(35.44))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.35, green: 0.86, blue: 0.68), lineWidth: 1)
            )
            .offset(x: 1.61, y: -12.66)
            .rotationEffect(.degrees(35.44))
        };Group {
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.95, green: 0.23, blue: 0.23), lineWidth: 1)
            )
            .offset(x: 71.61, y: -15.84)
            .rotationEffect(.degrees(-33.69))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.95, green: 0.23, blue: 0.23), lineWidth: 1)
            )
            .offset(x: 41.61, y: -15.84)
            .rotationEffect(.degrees(-33.69))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.95, green: 0.23, blue: 0.23), lineWidth: 1)
            )
            .offset(x: 15.61, y: -16.84)
            .rotationEffect(.degrees(-33.69))
          Rectangle()
            .foregroundColor(.clear)
            .frame(width: 7.21, height: 0)
            .overlay(
              Rectangle()
                .stroke(Color(red: 0.95, green: 0.23, blue: 0.23), lineWidth: 1)
            )
            .offset(x: -14.39, y: -17.84)
            .rotationEffect(.degrees(-33.69))
        }
      }
      .frame(width: 210, height: 69.68)
      .offset(x: 0.50, y: 293.84)
    }
    .frame(width: 393, height: 852)
    .background(Color(red: 1, green: 0.98, blue: 0.96));
  }
    
}

struct ContentView_Previews: PreviewProvider {
  static var previews: some View {
      ViewRegistro()
  }
}
